#consts for states 
PROCESS_STARTED = "PROCESS_STARTED"
EXITING = "EXITING"

INITALIALIZING_ENTERING = "INITAL_LOADING_ENTERING"
INITALIALIZING_DONE = "INITAL_LOADING_DONE"

MAIN_MENU_ENTERING = "MAIN_MENU_ENTERING"
MAIN_MENU_LEAVING = "MAIN_MENU_LEAVING"

MAIN_LOADING_STARTING = "MAIN_LOADING_STARTING"
MAIN_LOADING_DONE = "MAIN_LOADING_DONE"

GAME_LOOP_ENTERING = "GAME_LOOPING_ENTERING"
GAME_LOOP_LEAVING = "GAME_LOOPING_LEAVING"

PAUSE_MENU_ENTERING = "PAUSE_MENU_ENTERING"
PAUSE_MENU_LEAVING = "PAUSE_MENU_LEAVING"

ENDING_CREDITS_ENTERING = "ENDING_CREDITS_ENTERING"
ENDING_CREDITS_LEAVING = "ENDING_CREDITS_LEAVING"

QUIT = "QUIT"